import Head from "next/head";

export default function News({ posts, lastUpdated }) {
  return (
    <>
      <Head>
        <title>News | MyStore</title>
        <meta name="description" content="Latest news from MyStore" />
      </Head>
      <div className="max-w-4xl mx-auto p-8">
        <h1 className="text-3xl font-bold mb-2">News Updates</h1>
        <p className="text-gray-500 mb-6 text-sm">
          This page uses Incremental Static Regeneration (ISR) with a 10-second revalidation period.
        </p>

        <div className="bg-yellow-100 text-yellow-800 p-3 rounded mb-6 text-sm font-medium inline-block">
          Data Last Updated: {lastUpdated}
        </div>

        <div className="space-y-4">
          {posts.map((post) => (
            <div key={post.id} className="bg-white rounded shadow p-5">
              <h2 className="text-xl font-semibold mb-2 capitalize">{post.title}</h2>
              <p className="text-gray-700">{post.body}</p>
            </div>
          ))}
        </div>
      </div>
    </>
  );
}

export async function getStaticProps() {
  let posts = [];
  try {
    const res = await fetch("https://jsonplaceholder.typicode.com/posts?_limit=10");
    posts = await res.json();
  } catch (err) {
    console.error("Failed to fetch news posts:", err);
  }

  // Get current timestamp to demonstrate when the page was generated by Next.js
  const lastUpdated = new Date().toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
  });

  return {
    props: {
      posts,
      lastUpdated,
    },
    revalidate: 10, // Revalidate every 10 seconds
  };
}
